version: '3.8'
services:
  concurrency-db:
    image: mysql:8.0
    command: --transaction-isolation=READ-COMMITTED
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=concurrency-tutorial
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - '3306:3306'

  concurrency-redis:
    image: redis:6.0.9
    command: redis-server --requirepass test
    ports:
      - '6379:6379'